name: BMF News Monitor

on:
  schedule:
    - cron: '0 * * * *' # St√ºndlich
  workflow_dispatch: # Erlaubt manuellen Start

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Dependencies
        run: pip install requests beautifulsoup4

      - name: Run Monitor
        env:
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python bmf_monitor.py

      - name: Commit History
        run: |
          git config --global user.name "BMF-Bot"
          git config --global user.email "bot@bmf.de"
          git add bmf_history.json
          git commit -m "Update history" || echo "No changes"
          git push
