name: BMF Watcher
on:
  schedule:
    - cron: '0 * * * *' # Läuft jede Stunde
  workflow_dispatch: # Erlaubt manuelles Starten zum Testen

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # WICHTIG: Erlaubt dem Bot, die last_news.txt zu speichern
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Scraper
        env:
          # HIER WERDEN DIE SECRETS AN DAS SKRIPT ÜBERGEBEN
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_MAIL: ${{ secrets.SENDER_MAIL }}
        run: python scraper.py
      - name: Save Snapshot
        run: |
          git config --global user.name "BMF Bot"
          git config --global user.email "bot@github.com"
          git add last_news.txt || exit 0
          git commit -m "Update last news snapshot" || exit 0
          git push
